Ignore actions without cards
It appears that some actions do not have an associated card - this was
causing the script to fail on line 50 with:

    undefined method `[]' for nil:NilClass (NoMethodError)